<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://syn.bjca.com"
                  xmlns:intf="http://syn.bjca.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://syn.bjca.com">
    <!--
   WSDL created by Apache Axis version: 1.4
   Built on Apr 22, 2006 (06:55:48 PDT)
   -->
    <wsdl:message name="SynchronizedUserInfoRequest">
        <wsdl:part name="OperateID" type="xsd:int"/>
        <wsdl:part name="OperateCode" type="xsd:string"/>
        <wsdl:part name="OperateType" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="SynchronizedUserInfoResponse">
        <wsdl:part name="SynchronizedUserInfoReturn" type="xsd:boolean"/>
    </wsdl:message>
    <wsdl:portType name="SynchronizedDataInfoServiceImpl">
        <wsdl:operation name="SynchronizedUserInfo" parameterOrder="OperateID OperateCode OperateType">
            <wsdl:input message="impl:SynchronizedUserInfoRequest" name="SynchronizedUserInfoRequest"/>
            <wsdl:output message="impl:SynchronizedUserInfoResponse" name="SynchronizedUserInfoResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="extDataSynchronizedServiceSoapBinding" type="impl:SynchronizedDataInfoServiceImpl">
        <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="SynchronizedUserInfo">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="SynchronizedUserInfoRequest">
                <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://syn.bjca.com"
                               use="encoded"/>
            </wsdl:input>
            <wsdl:output name="SynchronizedUserInfoResponse">
                <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://syn.bjca.com"
                               use="encoded"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SynchronizedDataInfoServiceImplService">
        <wsdl:port binding="impl:extDataSynchronizedServiceSoapBinding" name="extDataSynchronizedService">
            <wsdlsoap:address location="http://localhost:8080/portal/services/extDataSynchronizedService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>